In [ ]:
import pandas as pd

df = pd.read_csv('data/P1.csv')

df.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,P1,08/08/2025,20:15,Casa Pia,Sp Lisbon,0,2,A,0,1,...,1.93,1.93,1.90,2.00,1.93,1.95,1.82,1.92,1.91,2.04
1,P1,09/08/2025,15:30,Nacional,Gil Vicente,0,2,A,0,2,...,1.80,2.05,1.89,2.02,1.83,2.05,1.78,1.97,1.87,2.12
2,P1,09/08/2025,20:30,Arouca,AVS,3,1,H,1,0,...,1.98,1.88,1.97,1.93,1.98,1.90,1.90,1.79,2.02,1.95
3,P1,10/08/2025,17:00,Famalicao,Santa Clara,3,0,H,2,0,...,1.93,1.93,2.00,1.90,1.93,1.93,1.78,1.89,1.93,2.05
4,P1,10/08/2025,20:30,Moreirense,Alverca,2,1,H,1,1,...,1.95,1.90,2.05,1.87,1.95,1.90,1.88,1.84,2.05,1.94

In [ ]:

print("Número de colunas originais:", len(df.columns))

colunas_importantes = ['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR']


df_limpo = df[colunas_importantes].copy()


df_limpo.head()

Número de colunas originais: 131

         Date    HomeTeam     AwayTeam  FTHG  FTAG FTR
0  08/08/2025    Casa Pia    Sp Lisbon     0     2   A
1  09/08/2025    Nacional  Gil Vicente     0     2   A
2  09/08/2025      Arouca          AVS     3     1   H
3  10/08/2025   Famalicao  Santa Clara     3     0   H
4  10/08/2025  Moreirense      Alverca     2     1   H

In [ ]:
import pandas as pd 


df_limpo['Date'] = pd.to_datetime(df_limpo['Date'], dayfirst=True)
df_limpo = df_limpo.sort_values(by='Date')


def calcula_pontos_casa(resultado):
    if resultado == 'H': 
        return 3
    elif resultado == 'D': 
        return 1
    else: 
        return 0


def calcula_pontos_fora(resultado):
    if resultado == 'A': 
        return 3
    elif resultado == 'D': 
        return 1
    else: 
        return 0


df_limpo['HomePoints'] = df_limpo['FTR'].apply(calcula_pontos_casa)
df_limpo['AwayPoints'] = df_limpo['FTR'].apply(calcula_pontos_fora)


df_limpo.head()

        Date    HomeTeam     AwayTeam  FTHG  FTAG FTR  HomePoints  AwayPoints
0 2025-08-08    Casa Pia    Sp Lisbon     0     2   A           0           3
1 2025-08-09    Nacional  Gil Vicente     0     2   A           0           3
2 2025-08-09      Arouca          AVS     3     1   H           3           0
3 2025-08-10   Famalicao  Santa Clara     3     0   H           3           0
4 2025-08-10  Moreirense      Alverca     2     1   H           3           0

In [4]:

df_limpo['HomeForm'] = 0
df_limpo['AwayForm'] = 0


pontos_totais = {}


for index, row in df_limpo.iterrows():
    casa = row['HomeTeam']
    fora = row['AwayTeam']
    
    
    if casa not in pontos_totais:
        pontos_totais[casa] = 0
    if fora not in pontos_totais:
        pontos_totais[fora] = 0
        
    
    df_limpo.at[index, 'HomeForm'] = pontos_totais[casa]
    df_limpo.at[index, 'AwayForm'] = pontos_totais[fora]
    
    
    pontos_totais[casa] += row['HomePoints']
    pontos_totais[fora] += row['AwayPoints']


df_limpo.head(15)

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HomePoints,AwayPoints,HomeForm,AwayForm
0,2025-08-08,Casa Pia,Sp Lisbon,0,2,A,0,3,0,0
1,2025-08-09,Nacional,Gil Vicente,0,2,A,0,3,0,0
2,2025-08-09,Arouca,AVS,3,1,H,3,0,0,0
3,2025-08-10,Famalicao,Santa Clara,3,0,H,3,0,0,0
4,2025-08-10,Moreirense,Alverca,2,1,H,3,0,0,0
5,2025-08-10,Sp Braga,Tondela,3,0,H,3,0,0,0
6,2025-08-11,Estoril,Estrela,1,1,D,1,1,0,0
7,2025-08-11,Porto,Guimaraes,3,0,H,3,0,0,0
8,2025-08-15,AVS,Casa Pia,0,2,A,0,3,0,0
11,2025-08-16,Estrela,Benfica,0,1,A,0,3,1,0
9,2025-08-16,Tondela,Famalicao,0,1,A,0,3,0,3
10,2025-08-16,Guimaraes,Estoril,3,2,H,3,0,0,1
12,2025-08-17,Rio Ave,Nacional,1,1,D,1,1,0,0
13,2025-08-17,Alverca,Sp Braga,0,3,A,0,3,0,3
14,2025-08-17,Santa Clara,Moreirense,0,1,A,0,3,0,3